package natac;

public enum GameState {
	MAIN_MENU, RULES, SETUP_PLAYERS, SETUP_NAMES, SETUP_VP, INITIAL_PLACEMENT, MAIN_GAME, BUILD_MENU, CANNON_TARGETING,
	PLAGUE_TARGETING, CARAVAN_SELECT, BANK_TRADE, WIN_SCREEN
}
